-- THOSE WITH AN AVERAGE DELAY OF 96 HOURS.
SELECT 
U.ID,U.NAMESURNAME,
AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_))

FROM ORDERS O 

INNER JOIN USERS U ON U.ID = O.USERID 
INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID 
INNER JOIN CITIES CT ON CT.ID = A.CITYID 
INNER JOIN TOWNS T ON T.ID = A.TOWNID 
INNER JOIN DISTRICTS D ON D.ID = A.DISTRICTID  
INNER JOIN PAYMENTS P ON P.ID = O.ID 
INNER JOIN INVOICES I ON I.ORDERID = O.ID 

GROUP BY
U.ID,U.NAMESURNAME  
HAVING AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_)) > 96
 
ORDER BY 3 DESC