-- SUBQUERY (SELECT IN SELECT) 

SELECT ITM.ITEMCODE AS ITEMCODE_,ITM.ITEMNAME AS ITEMNAME_, 
(SELECT MIN(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID = ITM.ID) AS MIN_PRICE,
(SELECT MAX(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID = ITM.ID) AS MAX_PRICE,
(SELECT AVG(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID = ITM.ID) AS AVG_PRICE,
(SELECT SUM(AMOUNT) FROM ORDERDETAILS WHERE ITEMID = ITM.ID) AS SUM_PRICE

FROM 

ITEMS ITM  
ORDER BY ITM.ITEMNAME