--AVERAGE DELIVERY TIME 

SELECT 
--O.ID,
--O.DATE_ AS ORDER_DATE, 
--I.DATE_ AS INVOICE, 
MIN(DATEDIFF(HOUR,O.DATE_,I.DATE_)) MIN_DELIVERY_TIME, 
MAX(DATEDIFF(HOUR,O.DATE_,I.DATE_)) MAX_DELIVERY_TIME,
AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_)) AS AVG_DELIVERY_TIME

FROM ORDERS O 

INNER JOIN USERS U ON U.ID = O.USERID 
INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID 
INNER JOIN CITIES CT ON CT.ID = A.CITYID 
INNER JOIN TOWNS T ON T.ID = A.TOWNID 
INNER JOIN DISTRICTS D ON D.ID = A.DISTRICTID  
INNER JOIN PAYMENTS P ON P.ID = O.ID 
INNER JOIN INVOICES I ON I.ORDERID = O.ID 

