--WHICH MONTHS SOLD THE MOST


SELECT ITM.ITEMCODE AS ITEMCODE_,ITM.ITEMNAME AS ITEMNAME_, 
(SELECT MIN(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID = ITM.ID) AS MIN_PRICE,
(SELECT MAX(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID = ITM.ID) AS MAX_PRICE,
(SELECT AVG(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID = ITM.ID) AS AVG_PRICE,
(SELECT SUM(AMOUNT) FROM ORDERDETAILS WHERE ITEMID = ITM.ID) AS SUM_PRICE

( 
SELECT TOP 1 DATEPART(MONTH,O.DATE_) AS MONTH_,SUM(AMOUNT) FROM ORDERDETAILS OD 
INNER JOIN ORDERS O ON OD.ORDERID = O.ID 
WHERE OD.ITEMID = 1 
GROUP BY DATEPART(MONTH,O.DATE_)  
ORDER BY SUM(AMOUNT) DESC
) 


FROM 

ITEMS ITM  
ORDER BY ITM.ITEMNAME