--DISTRIBUTION BY TYPE OF PAYMENT 

 SELECT 
 DATEPART (YEAR,DATE_) AS YEAR_,
 DATEPART (MONTH,DATE_) AS MONTH_,
 CASE 
    WHEN PAYMENTTYPE = 1 THEN 'CREDIT CARD' 
	WHEN PAYMENTTYPE = 2 THEN 'CASH' 
END AS PAYTYPE_EXP, 
 SUM(PAYMENTTOTAL) AS TOTALPAYMENT_
 FROM PAYMENTS 

 GROUP BY  DATEPART (MONTH,DATE_) ,PAYMENTTYPE,DATEPART(YEAR,DATE_) 

 ORDER BY  DATEPART (MONTH,DATE_) 
 